# Generated by Django 4.2 on 2024-08-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "description", "category", "price"],
                "permissions": [
                    ("can_edit_category", "Can edit category"),
                    ("can_edit_description", "Can edit description"),
                    ("can_edit_is_published", "Can edit is_published"),
                ],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
    ]
