# Generated by Django 4.2 on 2024-08-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0028_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="is_current",
            field=models.BooleanField(default=False, verbose_name="is current"),
        ),
        migrations.AlterField(
            model_name="version",
            name="number",
            field=models.PositiveIntegerField(verbose_name="version number"),
        ),
        migrations.AlterField(
            model_name="version",
            name="title",
            field=models.CharField(max_length=150, verbose_name="title"),
        ),
    ]
