# Generated by Django 4.2 on 2024-08-24 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created"],
                "verbose_name": "order",
                "verbose_name_plural": "orders",
            },
        ),
    ]
